=== fonhorst/sorcer/iGrid/modules/sorcer/src/main/java/sorcer/xml/data/fiperjob.dtd
<?xml version='1.0' encoding='us-ascii'?>

<!ELEMENT FiperJob (FiperContext+, FiperTask+)> 
<!ATTLIST FiperJob 
	name CDATA #REQUIRED
>
<!ELEMENT FiperContext (DataNode | TextNode)*>
<!ATTLIST FiperContext
	name CDATA #REQUIRED
>
<!ELEMENT DataNode (#PCDATA)>
<!ATTLIST DataNode
	path CDATA #REQUIRED
	fiperType CDATA #REQUIRED
	ioType CDATA "IN_TYPE"
	isTransient CDATA "true"
	data CDATA #REQUIRED
>
<!ELEMENT DataNode (#PCDATA)>
<!ATTLIST DataNode
	path CDATA #REQUIRED
	fiperType CDATA #REQUIRED
	ioType CDATA "IN_TYPE"
	isTransient CDATA "true"
	data CDATA #REQUIRED
>
<!ELEMENT TextNode (#PCDATA)>
<!ATTLIST TextNode
	path CDATA #REQUIRED
>
<!ATTLIST FiperTask
	name CDATA #REQUIRED
	description CDATA ""
	method CDATA #REQUIRED
	provider CDATA #REQUIRED
	
>
<!ELEMENT TaskContext (#PCDATA)>
<!ATTLIST TaskContext
	root CDATA #REQUIRED
>

=== fonhorst/sorcer/iGrid/modules/sorcer/src/main/java/sorcer/xml/data/autoshank.xml
<?xml version ="1.0" encoding="UTF-8"?>

<!DOCTYPE FiperJob SYSTEM "fiperjob.dtd">


<FiperJob name="autoshank job">

  <FiperContext name="shank">
    <DataNode path="GEOM/SHANK/MESH/DATA" ioType="IN_TYPE" fiperType="FIPER_DATA_MESH" 
      data="http://hippolyta.cs.ttu.edu/fiper/data/Shank_Tet_Mesh.dat">  TET </DataNode>
    <DataNode path="GEOM/SHANK/SHANK_PRT" ioType="IN_TYPE" fiperType="FIPER_AUTOSHANK_SEED" 
      data="http://hippolyta.cs.ttu.edu/fiper/data/AS_Shank_Prt.prt"> SEEDPART </DataNode>
    <DataNode path="GEOM/SHANK/SHANK_INP" ioType="IN_TYPE" fiperType="FIPER_AUTOSHANK_PARAMETERS" 
      data="http://hippolyta.cs.ttu.edu/fiper/data/AS_Inp.dat"> INP </DataNode>
  </FiperContext>

  <FiperContext name="System Context">
    <TextNode path="is master"> true </TextNode>
    <TextNode path="job/strategy"> sequential </TextNode>
    <TextNode path="job/strategy/access"> catalog </TextNode>
    <TextNode path="notify/execution/to:/Kao"> kao@cs.ttu.edu </TextNode>
    <TextNode path="no wait"> false </TextNode>
    <TextNode path="in/task/id"> kao-task-autoshank-1 </TextNode>
    <TextNode path="out/task/id"> id </TextNode>
  </FiperContext>

  <FiperTask name="Generate Solid Shank"
    description="Generate a solid shank from\na parametric data file and a seed part"
    method="autoshank"
    provider="AUTOSHANK">
    <TaskContext root="shank"> GEOM/SHANK </TaskContext>   
    <TaskContext root="System Context"> </TaskContext>
	</FiperTask>
</FiperJob>

=== fonhorst/sorcer/iGrid/modules/sorcer/src/sorcer/xml/data/testjob.xml
<?xml version ="1.0" encoding="UTF-8"?>

<!DOCTYPE FiperJob SYSTEM "fiperjob.dtd">

<FiperJob name="test job">
  
  <FiperContext name="DAS">
    <DataNode path="GEOM/SHANK/SHANK_PRT" fiperType="FIPER_AUTOSHANK_SEED" ioType="IN_TYPE" data="http://hippolta.cs.ttu.edu/fiper/data/AS_Shank_Prt.prt">SEEDPART</DataNode>
    <DataNode path="GEOM/SHANK/SHANK_INP" fiperType="FIPER_AUTOSHANK_PARAMETERS" ioType="IN_TYPE" data="http://hippolta.cs.ttu.edu/fiper/data/AS_Inp.prt">PARAMETER</DataNode>
    <TextNode path="GEOM/SHANK/OUT_PATH"> SHANK </TextNode>
  </FiperContext>
  
  <FiperContext name="System Context">
    <TextNode path="is master"> true </TextNode>
    <TextNode path="job/strategy"> sequential </TextNode>
    <TextNode path="job/strategy/access"> catalog </TextNode>
    <TextNode path="notify/execution/to:/Kao"> kao@cs.ttu.edu </TextNode>
    <!-- <TextNode path="no wait"> true </TextNode> -->
    <TextNode path="out/task/id"> id </TextNode>
  </FiperContext>

  <FiperTask name="Autoshank task" description = "performing autoshank operation" method="autoshank" provider="AUTOSHANK">
    <TaskContext root="DAS"> GEOM/SHANK </TaskContext>
    <TaskContext root="System Context"> </TaskContext>
  </FiperTask>

</FiperJob>

=== fonhorst/sorcer/iGrid/modules/sorcer/src/main/java/sorcer/xml/data/LLSAnalysis.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE FiperJob SYSTEM "http://hippolyta.cs.ttu.edu/fiper/data/xml/FiperJob.dtd">

<FiperJob name="Load/Lock Slot Analysis Job">

<FiperContext name="Translation">
<DataNode path="Translation Strategy" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.trans" data="http://hippolyta.cs.ttu.edu/fiper/data/lls/translation/llstranslation.dat"> Translation Strategy File </DataNode>
<DataNode path="CAD Geometry" ioType="IN_TYPE" fiperType="application/fiper.part.ug" data="http://hippolyta.cs.ttu.edu/fiper/data/lls/translation/cf34-10s4_lls.prt"> CAD Geometry File </DataNode>
</FiperContext>
<FiperContext name="Sys Context">
<TextNode path="in/task/id2"> 7d2b7167:e34c6811e0:-7ff9 </TextNode>
<TextNode path="in/task/id1"> 7d2b7167:e34c6811e0:-7ffa </TextNode>
<TextNode path="in/task/id0"> 7d2b7167:e34c6811e0:-7ffb </TextNode>
<TextNode path="out/task/id"> 7d2b7167:e34c6811e0:-7ffb </TextNode>
<TextNode path="is master"> true </TextNode>
<TextNode path="no wait"> true </TextNode><TextNode path="job/strategy/access"> catalog </TextNode>
<!-- <TextNode path="in/task/id5"> 7d2b7167:e34c6811e0:-7ff6 </TextNode> -->
<!-- <TextNode path="in/task/id4"> 7d2b7167:e34c6811e0:-7ff7 </TextNode> -->
<TextNode path="job/strategy"> sequential </TextNode>
<TextNode path="notify/execution/to:/peter.rohl"> peter.rohl@cs.ttu.edu </TextNode>
<TextNode path="notify/execution/to:/kevin.kao"> kao@cs.ttu.edu </TextNode>
<TextNode path="in/task/id3"> 7d2b7167:e34c6811e0:-7ff8 </TextNode>
</FiperContext>
<FiperTask name="Import UG Part File" description="Import UG context Model into Ansys" method="ugToAnsys" serviceType="fiper.service.ansys.UgToAnsysProtocol" provider="UG-ANSYS" taskId="7d2b7167:e34c6811e0:-7ffb">
<TaskContext root="Translation"></TaskContext>
<TaskContext root="Sys Context"></TaskContext>
</FiperTask>

<FiperContext name="Material">
<TextNode path="IN/PATH/Database File"> Translation/OUT/Database File </TextNode>
<DataNode path="Material Data" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.prep7" data="http://hippolyta/fiper/data/lls/material/llsmaterial.prep7"> Material Data File </DataNode>
</FiperContext>
<FiperTask name="Load Material Data" description="Load Material Data" method="executeAnsys" serviceType="fiper.service.ansys.AnsysProtocol" provider="ANSYS on SGI" taskId="7d2b7167:e34c6811e0:-7ffa">
<TaskContext root="Material"></TaskContext>
</FiperTask>

<FiperContext name="Meshing">
<DataNode path="Service Properties" ioType="IN_TYPE" fiperType=" " data="http://hippolyta/fiper/data/lls/meshing/llsmesh.serviceproperties"> Service Properties File </DataNode>
<TextNode path="IN/PATH/Database File"> Material/OUT/Database File </TextNode>
<DataNode path="Mesh/Amap Macro" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mac" data="http://hippolyta/fiper/data/lls/meshing/geamap.mac"> Amap Macro </DataNode>
<DataNode path="Mesh/MeshStrategy" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mesh" data="http://hippolyta/fiper/data/lls/meshing/llsmesh.dat"> Mesh Strategy Data </DataNode>
<DataNode path="Mesh/Mesh Blades" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mac" data="http://hippolyta/fiper/data/lls/meshing/mshbld.mac"> Mesh Blades </DataNode>
<DataNode path="Mesh/Vsweep Macro" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mac" data="http://hippolyta/fiper/data/lls/meshing/gesweep.mac"> Vsweep Macro </DataNode>
<DataNode path="Mesh/Spring Elements" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mac" data="http://hippolyta/fiper/data/lls/meshing/comnode.mac"> Spring Elements Macro </DataNode>
</FiperContext>
<FiperTask name="Mesh Model" description="Mesh LLS Model" method="mesh" serviceType="fiper.service.ansys.AnsysDiscretizationProtocol" provider="ANSYS on SGI" taskId="7d2b7167:e34c6811e0:-7ff9">
<TaskContext root="Meshing"></TaskContext>
</FiperTask>

<FiperContext name="Loads and BC">
<DataNode path="Blades Macro" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.mac" data="http://hippolyta/fiper/data/lls/loadsbc/fixblds.mac"> Blades Macro </DataNode>
<TextNode path="IN/PATH/Database File"> Meshing/OUT/Meshed Geometry </TextNode>
<DataNode path="Loads and BC Strategy" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.prep7" data="http://hippolyta/fiper/data/lls/loadsbc/llslbc.prep7"> LBC Strategy File </DataNode>
</FiperContext>
<FiperTask name="Apply Loads and BC" description="Apply Loads and Boundary Conditions" method="executeAnsys" serviceType="fiper.service.ansys.AnsysProtocol" provider="ANSYS on SGI" taskId="7d2b7167:e34c6811e0:-7ff8">
<TaskContext root="Loads and BC"></TaskContext>
</FiperTask>

<!--

<FiperContext name="Solution">
<TextNode path="IN/PATH/Database File"> Loads and BC/OUT/Database File </TextNode>
<DataNode path="Solution Strategy" ioType="IN_TYPE" fiperType="application/fiper.analysis.ansys.apdl" data="http://hippolyta/fiper/data/lls/solution/llssolve.apdl"> Solution Strategy File </DataNode>
</FiperContext>
<FiperTask name="Solve Model" description="Solve Model" method="executeAnsys" serviceType="fiper.service.ansys.AnsysProtocol" provider="ANSYS on SGI" taskId="7d2b7167:e34c6811e0:-7ff7">
<TaskContext root="Solution"></TaskContext>
</FiperTask>

<FiperContext name="PostProcessing">
<DataNode path="PostProcessing Strategy" ioType="IN_TYPE" fiperType=" " data="http://hippolyta/fiper/data/lls/postprocessing/llspost.apdl"> PostProcessing Strategy File </DataNode>
<TextNode path="IN/PATH/Results File"> Solution/OUT/Results File </TextNode>
<TextNode path="IN/PATH/Database File"> Solution/OUT/Database File </TextNode>
</FiperContext>
<FiperTask name="Load Material Data" description="Load Material Data" method="executeAnsys" serviceType="fiper.service.ansys.AnsysProtocol" provider="ANSYS on SGI" taskId="7d2b7167:e34c6811e0:-7ff6">
<TaskContext root="PostProcessing"></TaskContext>
</FiperTask>

-->

</FiperJob>
